### ISSUE TITLE
US 02.07.01 - Recipe screen with ListView

### ISSUE THREAD

**Issue by 5yph** [CMPUT301F22T11/Mealy#17]
**User story: As a meal planner, I want to see a list of my recipes.**

Similar to #9, we need to have an activity screen for our recipes. In addition, this screen should contain a listview that contains all our recipes, with specific identifying info for each element. This should also be dynamic and changed based off of our actions.

_Acceptance Criteria_

- [x] An activity must be created that represents the recipes screen
- [x] A listview should be in our activity
- [x] List items should contain title and serving size
- [ ] List items should have photos representing each item
- [x] Clicking on a list item should bring up a dialog box with the item name and three buttons: view, edit and delete. View refers to #14, edit refers to #15 and delete to #16
- [x] A button should be present that allows users to add recipes like in #11 
- [x] A sort dropdown should be present on the screen that allows the user to sort the list like in #18
- [x] List must be updated each time an item is edited, deleted or if the list itself is sorted.
