### ISSUE TITLE
US 04.01.01 - Shopping list screen with ListView

### ISSUE THREAD

**Issue by 5yph** [CMPUT301F22T11/Mealy#21]
**User story: As a meal planner, I want to view a shopping list of ingredients that I need to buy, based on my ingredient storage and meal plan.**

Similar to the rest of the listviews. we should have a shopping list activity screen with a ListView containing all the ingredients that the user needs to buy. This list should include details of each ingredient as well as an indication if it is being picked up or not.

_Acceptance Criteria_

- [x] An activity must be created that represents the shopping list screen
- [x] A listview should be in our activity
- [x] List items should contain details (refer to #22)
- [x] List items should have photos representing each item
- [x] List items should have an interactable checkbox that indicates if the user has bought that ingredient (refer to #24)
- [x] A button should be present that adds all checked ingredients to the ingredient storage
- [x] A sort dropdown should be present on the screen that allows the user to sort the list (refer to #23)
- [x] List must be updated each time an item is edited, deleted or if the list itself is sorted.
