### ISSUE TITLE
US 01.05.01 - Ingredients screen with ListView

### ISSUE THREAD

**Issue by 5yph** [CMPUT301F22T11/Mealy#9]
**User story: As a meal planner, I want to see a list of my ingredients.**

We need to have an activity screen for our ingredients. In addition, this screen should contain a listview that contains all our ingredients, with specific identifying info for each element. This should also be dynamic and changed based off of our actions.

_Acceptance Criteria_

- [ ] An activity must be created that represents the ingredients screen
- [ ] A listview should be in our activity
- [ ] List items should contain title, description, location, unit and amount
- [ ] List items should have photos representing each item
- [ ] Clicking on a list item should bring up a dialog box with the item name and three buttons: view, edit and delete. View refers to #6, edit refers to #7, and delete to #8.
- [ ] A button should be present that allows users to add ingredients like in #5 
- [ ] A sort dropdown should be present on the screen that allows the user to sort the list like in #10 
- [ ] List must be updated each time an item is edited, deleted or if the list itself is sorted.

**Comment by JakobLau9** [comment]
- [ ] Added JUnit Testing
